### ISSUE TITLE
有没有可能在Win和Linux共用一个数据文件

### ISSUE THREAD

**Issue by redleafnew** [rocket049/secret-diary#3]
不错的软件，谢谢。
不知道现在有没有这个功能，
在Win和Linux共用一个数据文件。
例如我昨天在Win下写下日记，今天接着用Linux下写，用Linux打开软件后，可以显示昨天在Win写的东西，同时可以编辑、删除昨天日记。当然也可以接着写今天的日记。

就是形成的日记文件位置可以自定义，放到NTFS分区。可以同时用Win和Linux下的程序打开编辑。

**Comment by redleafnew** [comment]
现在是不是只能导出加密日记，然后在另一个系统中再导入？

如果可以自定义位置，那么我可以将数据文件放在同步盘上，实现网络同步。

**Comment by rocket049** [comment]
你可以用软链接实现你的需要，先在windows中运行软件，然后在linux中运行下面的命令：
```
1、删除 linux 中的 ~/.sdiary
rm -rf ~/.sdiary
2、把windows中的 .sdiary 软链接到 ~/.sdiary
ln -s /media/盘符/windows中的.sdiary目录 ~/.sdiary
```

windows中的.sdiary目录可以点击“帮助”->“备份和删除”查看到。

**Comment by rocket049** [comment]
我将在1.2.10版实现楼主要求的功能

**Comment by redleafnew** [comment]
谢谢。
